### ISSUE TITLE
how to compile on Fedora 40

### ISSUE THREAD

**Issue by saeedsltm** [INGV/hypoellipse#1]
Dear @vlauciani @matteoquintiliani 
Since there is no fort77 on new Fedora versions +40, could you please suggest how to compile the code of this platform? Using gfrotran generates many errors despite using the flag --std=legacy.

Regards

**Comment by vlauciani** [comment]
Dear @saeedsltm 

Thank you for your message.

Since this project is designed to run within a Docker container, you don’t need `fort77` or any specific dependencies installed on your Fedora server, except for Docker itself. You can simply use the pre-built Docker image available on DockerHub:
```sh
$ docker pull ingv/hypoellipse:latest
```

Alternatively, you can build the Docker image locally:
```sh
$ docker build --tag ingv/hypoellipse .
```

Please make sure to review the project's README for detailed instructions and troubleshooting tips.

Best regards,
Valentino
